---
- hosts: all
  connection: local
  become: true
  tasks:
    - name: install dependency
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
    - name: add GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: add apt repository docker
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
    - name: install docker
      apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
    - name: make sure that docker was started and enabled
      service:
        name: docker
        state: started
        enabled: yes
    - name: Create docker group
      group:
        name: "docker"
        state: present

    - name: Adding user ivn to docker group  
      user:
        name: "ivn"
        groups: "docker"
        append: "yes"

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.25.0/docker-compose-Linux-x86_64
        dest: "/usr/local/bin/docker-compose"
        mode: 0755
    - name: Clone a public repository into ~/docker.
      git:
        repo: https://github.com/Iwandoin/todo-docker.git
#        version: main
        dest: ~/docker
        accept_hostkey: yes
    - name: Clone a public repository into ~/docker/todo-backend.
      git:
        repo: https://github.com/Iwandoin/todo-backend.git
#        version: main
        dest: ~/docker/todo-backend
        accept_hostkey: yes
    - name: Clone a public repository into ~/docker/todo-frontend
      git:
        repo: https://github.com/Iwandoin/todo-frontend.git
#        version: main
        dest: ~/docker/todo-frontend
        accept_hostkey: yes
    - name: run the service defined in my_project's docker-compose.yml
      command: docker-compose -f ~/docker/docker-compose.prod.yml up -d --build
      
