- name: Disable SELinux
  selinux:
    state: disabled
  when: ansible_distribution == 'CentOS' and ansible_selinux.status == "enabled"
- name: Reboot host and wait for it to restart
  reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
  when: ansible_distribution == 'CentOS' and ansible_selinux.status == "enabled"
