- name: Install postgres
  yum:
    name: ['postgresql-server', 'postgresql', 'python3', 'python3-pip', 'python3-psycopg2']
    update_cache: true
    state: present


- name: Find out if PostgreSQL is initialized
  stat:
    path: "/var/lib/pgsql/data/pg_hba.conf"
  register: postgres_data

- name: "Initialize PostgreSQL"
  shell: "postgresql-setup --initdb --unit postgresql"
  when: postgres_data.stat.isdir is not defined

- name: enabling postgresql services
  service:
    name: postgresql
    state: started
    enabled: yes


- name: Create first database
  postgresql_db:
    state: present
    name: "{{ db_name }}"
  become: yes
  become_user: postgres

- name: Create db user
  postgresql_user:
    state: present
    name: "{{ db_user }}"
    password: "{{ db_password }}"
  become: yes
  become_user: postgres

- name: "Grant db user access to app db"
  postgresql_privs:
    type: database
    database: "{{ db_name }}"
    roles: "{{ db_user }}"
    grant_option: yes
    privs: all
  become: yes
  become_user: postgres

- name: "Allow md5 connection for the db user"
  postgresql_pg_hba:
    dest: "~/data/pg_hba.conf"
    contype: host
    databases: all
    method: md5
    users: "{{ db_user }}"
    create: true
  become: yes
  become_user: postgres
- name: enabling postgresql services
  service:
    name: postgresql
    state: restarted
    enabled: yes