- name: install pip
  yum:
    name:
      - python3-pip
      - git
      - bash
      - virtualenv
    state: latest
    update_cache: yes
- name: Clone a public repository into ~/todo-backend.
  git:
    repo: https://github.com/Iwandoin/todo-backend.git
    #version: main
    dest: ./todo-backend/
    accept_hostkey: yes
    force: yes
- name: install dependency
  pip:
    state: present
    virtualenv: /home/vagrant/venv
    requirements: /home/vagrant/todo-backend/requirements.txt
- name: Create python symlink to python
  file:
    src: "/usr/bin/python3"
    dest: "/usr/bin/python"
    state: link

- name: migrate database
  django_manage:
    command: migrate
    app_path: todo-backend/backend
    virtualenv: /home/vagrant/venv
  register: migrate
  environment:
    DEBUG: 0
    DJANGO_ALLOWED_HOSTS: '*'
    SQL_ENGINE: django.db.backends.postgresql
    SQL_DATABASE: backend
    SQL_USER: backend
    SQL_PASSWORD: backendbackend
    SQL_HOST: localhost
    SQL_PORT: 5432
    SECRET_KEY: kx8hi*n!9@^7m2z5hi!0pdw%3q=h@sn0el^i+g4u59=*g_uw$e
    DATABASE: postgres
    AWS_S3_ACCESS_KEY: ''
    AWS_S3_SECRET_KEY: ''
- name: Gunicorn run
  gunicorn:
    app: 'backend.wsgi'
    chdir: /home/vagrant/todo-backend/backend
    virtualenv: /home/vagrant/venv
  environment:
    DEBUG: 0
    DJANGO_ALLOWED_HOSTS: '*'
    SQL_ENGINE: django.db.backends.postgresql
    SQL_DATABASE: backend
    SQL_USER: backend
    SQL_PASSWORD: backendbackend
    SQL_HOST: localhost
    SQL_PORT: 5432
    SECRET_KEY: kx8hi*n!9@^7m2z5hi!0pdw%3q=h@sn0el^i+g4u59=*g_uw$e
    DATABASE: postgres
    AWS_S3_ACCESS_KEY: ''
    AWS_S3_SECRET_KEY: ''